on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  docker-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Dockerfile using Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile # only ask for dockerfile scans
          quiet: true # show only failed checks
          container_user: 1000 # UID to run the container under
          # to prevent permission issues
      # Hadolint
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ./Dockerfile
          failure-threshold: error
      - name: Print Hadolint lint results
        run: echo 'HADOLINT LINT RESULTS => ${{ env.HADOLINT_RESULTS }}'

