name: 01 Lint Dockerfile
on: push
jobs:
  dockerfile-linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
